name: build dapp

on:
  push:
   branches:
    - master

jobs:
  build:
   runs-on: ubuntu-latest
   name: Build and Push
   steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false

    - name: git-checkout
      uses: actions/checkout@v3
    
    - name: Build
      run: pnpm install
      run: pnpm dist
      
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
